// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"chunkof_Utility","status":true,"description":"Utility methods.","parameters":{}},
{"name":"chunkof_SaveControl","status":true,"description":"","parameters":{}}
];
